name: Clojure CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Clojure
        uses: DeLaGuardo/setup-clojure@master
        with:
          cli: 1.10.3.1040

      - name: Install clj-kondo
        run: npm install -g clj-kondo
        
      # - name: "Lint with clj-kondo"
      #   run: clj-kondo --lint src test --config .clj-kondo/config-ci.edn
          
      # - name: "Check Clojure Style"
      #   run: cljstyle check --report

      - name: Run Unit tests
        run: clojure -X:test/run

