name: Clojure CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Clojure
        uses: Luminus-Framework/lein-template@v3
        with:
          lein_version: '2.9.1'

      - name: Run tests
        run: lein test